### PR TITLE
Fix ital glyph order

### PR DESCRIPTION
**Pull request by djrrb**
this was a weird error, but after resetting some stuff i think it works now

### CODE REVIEW

**Comment by djrrb** [comment]
sorry i submitted this to the wrong repo!

**Comment by solmatas** [comment]
Hi @pichotta  and @djrrb 
I corrected the exclamation marks, question, Eth and tbar.
I modified the version number and now t is v1.010 
https://github.com/solmatas/BitterPro

**Comment by pichotta** [comment]
@solmatas 
The most current source data is here:
https://github.com/TypeNetwork/Bitter

It is currently being reviewed for acceptance. How do you want to handle the exclamation marks, question, Eth and tbar?  What was corrected?

**Comment by solmatas** [comment]
Dear Jill
Thanks for letting us know. I just wanted to inform the changes I made and ask how to proceed.
There are pretty simple changes in both masters (Romand and Italic files):
- Eth
- tbar
- exclamdown
- exclam
- exclamdouble
- exclamdown.case
- exclam.sc
- exclamdown.sc
- questiondown
- question
- questiondown.case
- questiondown.sc
- question.sc

Also this was v. 1.000 and changed to:
Version: 1.010

If you need help with this I can do them, should I submit a PR in https://github.com/TypeNetwork/Bitter/ or do you prefer to make them directly? 

Thanks

**Comment by pichotta** [comment]
Hi Sol,  

Thanks for the list. I will see what I can do to incorporate these changes. Currently we are in a Robofont environment. The open corner feature in Glyphs does not port well back and forth between apps. Thanks for your offer to help. I will let you know. Here is the recent commit history. https://github.com/TypeNetwork/Bitter/commits/master

Best,

Jill

**Pull request closed without merging**
